"""극동방송 1분 칼럼 — 편별 원고·장면·표지 설정 (음원은 로고송을 잘라 낸 본문, 자막 시간은 *_자막.srt).
새 컴퓨터·새 세션에서도 이 폴더만 있으면 5편을 다시 만들 수 있다: python jobs/1분칼럼/run.py"""
from pathlib import Path
HERE = Path(__file__).resolve().parent
def f(tag): return str(HERE / f"{tag[2:6] if tag.startswith('26') else tag}_voice.m4a")
OUTRO = {"lines": ["FEBC 1분 칼럼,", "100만 일터선교사 양성을 꿈꾸는 SaGA 일터선교 글로벌 네트워크 아카데미와 함께했습니다."],
         "prompt": "a city skyline at early sunrise seen from a quiet hill, soft golden morning, calm and hopeful"}
EPS = [
 {"key": "0824", "cover_scene": 1, "audio": f("260824"), "start": 0.0, "end": 0, "speaker": "오정현 총장",
  "rows": ["일은 저주다?", "아닙니다"], "hand": "\"에덴에서부터 있었던 축복\"",
  "scenes": [
   {"lines": ["일은 하나님을 온전히 닮아 가는 거룩한 도구가 될 수 있습니다."],
    "prompt": "a set of well-worn carpenter's tools (hand plane, chisels, mallet) laid neatly on a sunlit wooden workbench with curls of wood shavings, warm morning light"},
   {"lines": ["나의 일을 통하여 하나님의 창조 사역이 완성되는 것입니다."],
    "prompt": "a freshly thrown wet terracotta clay pot sitting on a potter's wheel in a sunlit pottery studio, clay tools beside it, no flowers"},
   {"lines": ["대부분 예수 믿는 분들도 이 세상의 일이라는 것은", "범죄 이후에 저주로 주어진 것이다라는 생각이 많아요."],
    "prompt": "an empty office desk at night piled with paperwork, a glowing monitor and an empty chair, cold blue light"},
   {"lines": ["일은 아담의 타락 이후 인류 역사에 끼어든 저주의 결과물이 아니라"],
    "prompt": "cracked dry ground with thorns and thistles under a heavy grey sky, muted colors, wide shot"},
   {"lines": ["창조하실 때부터 하나님의 정원 에덴에 존재했던 축복의 일부였다."],
    "prompt": "a lush garden at sunrise with fruit trees, dew on the leaves and a clear stream, golden light through the branches"},
   {"lines": ["그리고 일은 불순종의 징벌로 주어진 것이 아니라", "축복의 일부이고,"],
    "prompt": "a small green seedling sprouting from dark rich soil, macro shot, morning light"},
   {"lines": ["하나님이 지금도 일하시기 때문에 우리가 지금도 일하는 것이에요."],
    "prompt": "a city skyline at sunrise with office windows lighting up and construction cranes at work, wide shot"},
   {"lines": ["하나님이 내게 맡기신 그 일을 기쁘게, 즐겁게 하는 사람이", "믿음 좋은 사람이에요."],
    "prompt": "fresh golden loaves of bread cooling on a wooden rack in a warm sunlit bakery"},
   {"lines": ["하나님의 영광 위하여, 일터의 온전함을 향해 달려가고", "창조 사역에 동참하는",
              "우리 온 성도님 될 수 있도록 붙잡아 주시기를 소망합니다."],
    "prompt": "an open bible beside a laptop and a mug on an office desk, soft morning window light"},
   OUTRO]},

 {"key": "0831", "cover_scene": 4, "audio": f("260831"), "start": 0.0, "end": 0, "speaker": "오정현 총장",
  "rows": ["하나님이 지금도 일하시니", "우리도 *일합니다*"], "hand": "\"일은 창조의 축복\"", "title_pt": 91,
  "scenes": [
   {"lines": ["일은 하나님을 온전히 닮아 가는 거룩한 도구가 될 수 있습니다."],
    "prompt": "a set of well-worn carpenter's tools (hand plane, chisels, mallet) laid neatly on a sunlit wooden workbench with curls of wood shavings, warm morning light"},
   {"lines": ["일은 아담의 타락 이후 인류의 역사에 끼어든 저주의 결과물이 아니라"],
    "prompt": "cracked dry ground with thorns and thistles under a heavy grey sky, muted colors, wide shot"},
   {"lines": ["창조하실 때부터 하나님의 정원 에덴에 존재했던 축복의 일부였다."],
    "prompt": "a lush garden at sunrise with fruit trees, dew on the leaves and a clear stream, golden light through the branches"},
   {"lines": ["그리고 일은 불순종의 징벌로 주어진 것이 아니라", "축복의 일부이고,"],
    "prompt": "a small green seedling sprouting from dark rich soil, macro shot, morning light"},
   {"lines": ["하나님이 지금도 일하시기 때문에", "우리가 지금도 일하는 것이에요."],
    "prompt": "a city skyline at sunrise with office windows lighting up and construction cranes at work, wide shot"},
   {"lines": ["나의 일을 통하여 하나님의 창조 사역이 완성되는 것입니다."],
    "prompt": "a freshly thrown wet terracotta clay pot sitting on a potter's wheel in a sunlit pottery studio, clay tools beside it, no flowers"},
   {"lines": ["하나님이 내게 맡기신 그 일을 기쁘게, 즐겁게 하는 사람이", "믿음 좋은 사람이에요."],
    "prompt": "fresh golden loaves of bread cooling on a wooden rack in a warm sunlit bakery"},
   {"lines": ["하나님의 영광 위하여, 일터의 온전함을 향해 달려가고", "창조 사역에 동참하는",
              "우리 온 성도님 될 수 있도록 붙잡아 주시기를 소망합니다."],
    "prompt": "an open bible beside a laptop and a mug on an office desk, soft morning window light"},
   OUTRO]},

 {"key": "0907", "cover_scene": 1, "audio": f("260907"), "start": 0.0, "end": 0, "speaker": "오정현 총장",
  "rows": ["예수님의 일 철학", "*세 가지*"], "hand": "\"사명\" \"연대\" \"이타\"",
  "scenes": [
   {"lines": ["일은 하나님을 온전히 닮아 가는 거룩한 도구가 될 수 있습니다."],
    "prompt": "a set of well-worn carpenter's tools (hand plane, chisels, mallet) laid neatly on a sunlit wooden workbench with curls of wood shavings, warm morning light"},
   {"lines": ["그걸 위하여 예수님의 일 철학이 필요해요."],
    "prompt": "an old carpenter's workshop in Nazareth with a half-finished wooden table, sawdust in a beam of sunlight through the doorway, no people"},
   {"lines": ["주님의 일 철학 첫 번째는", "내가 하는 그 일이 하나님의 일이라는 사명의식이 있었어요."],
    "prompt": "a single lit candle on a wooden desk beside an open notebook and pen, dawn light through the window"},
   {"lines": ["하나님과 같이 일한다는 연대의식이 있었어요."],
    "prompt": "two wooden chairs side by side at one workbench in a sunlit workshop, tools shared between them"},
   {"lines": ["이 일을 통하여 남들을 세우고 살린다는 이타적 동기가 있었어요."],
    "prompt": "a basket of fresh bread and a jug of water left on a doorstep in warm morning light"},
   {"lines": ["나의 일을 통하여 하나님의 창조 사역이 완성되는 것입니다."],
    "prompt": "a freshly thrown wet terracotta clay pot sitting on a potter's wheel in a sunlit pottery studio, clay tools beside it, no flowers"},
   {"lines": ["하나님이 내게 맡기신 그 일을 기쁘게, 즐겁게 하는 사람이", "믿음 좋은 사람이에요."],
    "prompt": "fresh golden loaves of bread cooling on a wooden rack in a warm sunlit bakery"},
   {"lines": ["하나님의 영광 위하여, 일터의 온전함을 향해 달려가고", "창조 사역에 동참하는",
              "우리 온 성도님 될 수 있도록 붙잡아 주시기를 소망합니다."],
    "prompt": "an open bible beside a laptop and a mug on an office desk, soft morning window light"},
   OUTRO]},
 {"key": "0914", "cover_scene": 1, "audio": f("260914"), "start": 0.0, "end": 0, "speaker": "오정현 총장",
  "rows": ["성경 최초 성령 충만", "그는 *일꾼*이었다"], "hand": "\"브살렐, 출애굽기 31장\"",
  "scenes": [
   {"lines": ["성경에서 최초로 성령 충만하다고 직접 언급된 분이", "누군지 아십니까?"],
    "prompt": "an old leather-bound bible lying open on a wooden table by a window, thin pages lit by soft daylight"},
   {"lines": ["브살렐을 지명하여 부르시고", "하나님의 영을 그에게 충만하게 하여"],
    "prompt": "an ancient goldsmith's workbench inside a desert tent: small hammer, chisels, a sheet of gold and a glowing oil lamp"},
   {"lines": ["그는 선지자도, 제사장도, 왕도, 사도도 아니었어요.", "일꾼이었어요."],
    "prompt": "a steel wood chisel and a round wooden mallet lying on a pile of curly wood shavings on a workbench, close-up, dusty sunbeam"},
   {"lines": ["하나님의 영을 그에게 충만하게 했다는 표현이", "모세도, 노아도, 아브라함도 아닌", "브살렐에게 임했다는 사실이",
              "시사하는 바가 많은 거예요."],
    "prompt": "seven small clay oil lamps burning in a row on an ancient stone table, warm flames, dark background, still life, no statues, no figures"},
   {"lines": ["지혜와 총명과 지식과 여러 가지 재주로", "정교하게, 이렇게 되어 가지고"],
    "prompt": "macro shot of intricately engraved gold with almond blossom patterns beside fine engraving tools, warm light"},
   {"lines": ["여러분과 우리 모두에게", "창조적인 일의 능력이 확산되는 것이에요."],
    "prompt": "a bright modern design studio with sketches, tablets and green plants on sunlit desks, no one in the room"},
   {"lines": ["하나님이 내게 맡기신 그 일을 기쁘게, 즐겁게 하는 사람이", "믿음 좋은 사람이에요."],
    "prompt": "a finished handmade wooden chair standing in a sunlit carpentry workshop, sawdust floating in the light"},
   {"lines": ["하나님의 영광 위하여, 일터의 온전함을 향해 달려가고", "창조 사역에 동참하는",
              "우리 온 성도님 될 수 있도록 붙잡아 주시기를 소망합니다."],
    "prompt": "a pair of worn leather work gloves lying beside a small closed bible on a wooden workbench, morning light, still life"},
   OUTRO]},
 {"key": "0921", "cover_scene": 2, "audio": f("260921"), "start": 0.0, "end": 0, "speaker": "이돈주 학장",
  "rows": ["나는 작은 부품일까?", "하나님은 *태도*를 보십니다"], "hand": "\"주께 하듯 하라, 골로새서 3:23\"",
  "scenes": [
   {"lines": ["오늘도 일하시는 동안 이런 생각이 들지 않으셨나요?"],
    "prompt": "a tall office window at dusk overlooking city lights, an empty chair facing the window"},
   {"lines": ["나는 왜 이 일을 하고 있을까?", "내가 하는 일이 정말 의미가 있을까?"],
    "prompt": "a desk with stacks of paperwork and a cold cup of coffee under a desk lamp, late evening"},
   {"lines": ["나는 조직 안의 작은 부품에 불과한 것은 아닐까?"],
    "prompt": "macro shot of many brass gears inside a large machine, one small gear in sharp focus"},
   {"lines": ["그러나 성경은 우리의 일을 다르게 보게 합니다.", "무슨 일을 하든지 마음을 다하여 주께 하듯 하라."],
    "prompt": "an open bible on an office desk beside a laptop, morning sunlight through window blinds"},
   {"lines": ["회사가 나를 평가하기 전에", "하나님은 나의 태도를 보십니다."],
    "prompt": "a spotless office lobby floor gleaming in early morning light, a mop and bucket standing to the side"},
   {"lines": ["사람이 알아주기 전에", "하나님은 나의 성실을 보십니다."],
    "prompt": "a single small precision metal part on a workbench under a magnifying lamp, warm light"},
   {"lines": ["작아 보이는 일도 하나님 앞에서 감당하면", "믿음의 자리가 됩니다."],
    "prompt": "wooden shelves of a small grocery shop neatly stocked with glass jars, bread and fruit, soft morning light"},
   {"lines": ["직급이 낮아도 괜찮습니다.", "눈에 띄지 않아도 괜찮습니다."],
    "prompt": "cardboard boxes stacked along a sunlit office corridor, long shadows"},
   {"lines": ["하나님께서 맡기신 자리라면", "그곳은 결코 작은 자리가 아닙니다."],
    "prompt": "a single desk and chair by a large window with morning sun, a small green plant on the desk"},
   {"lines": ["오늘 내가 선 그 일터에서", "맡겨진 일을 주께 하듯 감당하며", "믿음으로 승리하시기 바랍니다."],
    "prompt": "a modern office building entrance at sunrise, glass doors reflecting golden light, empty street"},
   OUTRO]},
]
