-- 자동 생성 파일: npm run seed:generate (src/content/* 기준). 직접 수정하지 말 것.
-- 감염병 콘텐츠는 in_review 상태로 들어가며, 관리자 CMS에서 검수자·검토일을 기록해 승인·게시해야 공개된다.
-- 시설은 모두 예시 데이터(is_example=true)다.
begin;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('89a0fc4e-eb7b-5dce-ae1c-7cb3d14c9f30', 'dog_registration_check', 'dog', null, 'legal', '동물등록 여부 확인하기', '2개월령 이상 반려견은 동물등록이 의무입니다. 등록 대행 동물병원이나 시·군·구청에서 할 수 있어요.', '{"species":"dog","registrationStatus":["not_registered","unknown"],"repeat":null}'::jsonb, 'legal', 1, 'easylaw_pet', 'https://easylaw.go.kr/CSP/CnpClsMain.laf?ccfNo=2&cciNo=2&cnpClsNo=1&csmSeq=1809&popMenu=ov', '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('ad6c9c04-5100-58e1-888e-caf4df925e52', 'dog_tag_check', 'dog', null, 'legal', '인식표(이름·연락처) 확인', '외출 시 소유자 연락처가 적힌 인식표를 달아야 합니다. 목걸이 상태와 글씨가 지워지지 않았는지 살펴보세요.', '{"species":"dog","repeat":"monthly"}'::jsonb, 'legal', 1, 'easylaw_pet', 'https://easylaw.go.kr', '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('02438fc5-0ab9-5b24-9a1d-8c88022854b2', 'dog_walk_kit', 'dog', null, 'outdoor', '산책 전 목줄·배변봉투·물 챙기기', '목줄(2m 이내)·배변봉투는 법정 의무입니다. 더운 날엔 물과 노면 온도도 확인하세요.', '{"species":"dog","repeat":"daily"}'::jsonb, 'safety', 1, 'easylaw_pet', 'https://easylaw.go.kr', '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('0ba69971-4218-5b8b-830e-7ac4bccca5d1', 'dog_tick_check', 'dog', null, 'outdoor', '산책 후 진드기 확인·빗질', '풀숲을 다녀왔다면 귀 뒤·겨드랑이·발가락 사이를 살펴보세요. 진드기는 손으로 터뜨리지 말고 동물병원에 문의하세요.', '{"species":"dog","months":[3,4,5,6,7,8,9,10,11],"repeat":"daily"}'::jsonb, 'safety', 1, 'kdca_sfts', 'https://dportal.kdca.go.kr', '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('6ce61018-6492-5352-a62f-460a2d3277de', 'daily_observation', null, null, 'health', '식욕·음수·배변·행동 변화 기록', '평소와 다른 점이 있으면 기록해 두세요. 병원에 갈 때 가장 도움이 되는 정보입니다.', '{"repeat":"daily"}'::jsonb, 'health', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('b11e4159-3ece-5811-a6b2-a3754d94d936', 'weekly_weight', null, null, 'health', '체중 재서 기록하기', '같은 시간·같은 저울로 재면 변화를 알아차리기 쉬워요.', '{"repeat":"weekly"}'::jsonb, 'health', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('57db0e5c-ac36-5159-8dce-b1f720da2d7f', 'senior_watch', null, 'senior', 'health', '노령 반려동물 음수량·활동량 살피기', '물을 갑자기 많이 마시거나 움직임이 줄면 기록하고 동물병원과 상담하세요.', '{"lifeStage":["senior"],"repeat":"weekly"}'::jsonb, 'health', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('10de6972-99b1-594d-9feb-d59059c2a499', 'home_poison_check', null, null, 'poison', '집안 위험 물질 점검', '사람 약, 초콜릿, 포도, 자일리톨, 양파, 세제, 백합류 식물이 손 닿는 곳에 있는지 확인하세요.', '{"repeat":"monthly"}'::jsonb, 'safety', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('b213c80c-3421-5bdc-af1f-9bca33ca5c91', 'cat_litter', 'cat', null, 'cat_env', '화장실 청소 (매일)', '매일 치우면 배변 변화도 빨리 알 수 있고, 톡소포자충 예방에도 도움이 됩니다. 장갑을 끼고 손을 씻으세요.', '{"species":"cat","repeat":"daily"}'::jsonb, 'health', 1, 'kdca_toxo', 'https://dportal.kdca.go.kr', '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('6ab9ed14-4e18-540a-ad05-8a975453fab7', 'cat_env_check', 'cat', null, 'cat_env', '수직공간·숨을 곳·끈류 점검', '올라갈 곳과 숨을 곳이 있는지, 실·끈·고무줄이 바닥에 떨어져 있지 않은지 살펴보세요.', '{"species":"cat","repeat":"monthly"}'::jsonb, 'general', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('36dca07f-4664-5d9a-807b-9d94f33826eb', 'multi_pet_watch', null, null, 'behavior', '다동물 가정: 식사·화장실 따로 쓰는지 확인', '서로 눈치 보며 못 먹거나 화장실을 피하면 스트레스 신호일 수 있어요.', '{"multiPet":true,"repeat":"weekly"}'::jsonb, 'lifestyle', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.care_task_templates (id, key, species, life_stage, category, title, description, rule_json, priority, version, source_id, source_url, reviewed_at, status) values ('7ef37a13-a6f1-56fd-9a47-784ccf6fcad9', 'insurance_renewal', null, null, 'insurance', '보험 갱신일·청구 서류 확인', '갱신일이 다가오면 보장 내용이 바뀌는지 보험사 고객센터에서 확인하세요.', '{"insuranceStatus":["insured"],"repeat":"monthly"}'::jsonb, 'lifestyle', 1, null, null, '2026-08-31', 'published') on conflict (key) do update set title = excluded.title, description = excluded.description, rule_json = excluded.rule_json, priority = excluded.priority, version = excluded.version, reviewed_at = excluded.reviewed_at;
insert into public.content_cards (id, slug, content_type, species, status) values ('9ad9556a-0b04-51e6-a785-f5d8bc58b293', 'sfts', 'zoonosis', array['dog','cat','human']::text[], 'in_review') on conflict (slug) do nothing;
insert into public.content_cards (id, slug, content_type, species, status) values ('02ac3db8-4c00-55b4-910f-dd68afe38976', 'rabies', 'zoonosis', array['dog','cat','human']::text[], 'in_review') on conflict (slug) do nothing;
insert into public.content_cards (id, slug, content_type, species, status) values ('470b77e0-bf38-561b-844c-42f028ebe5c7', 'canine-brucellosis', 'zoonosis', array['dog','human']::text[], 'in_review') on conflict (slug) do nothing;
insert into public.content_cards (id, slug, content_type, species, status) values ('4b9dadea-8d55-5935-bcbf-3b44a45a9437', 'toxoplasmosis', 'zoonosis', array['cat','human']::text[], 'in_review') on conflict (slug) do nothing;
insert into public.content_versions (id, content_id, version, title, summary, body_json, source_json, author_name, status, change_reason) values ('02896c65-1c7c-5214-a35b-0866a9ecef42', '9ad9556a-0b04-51e6-a785-f5d8bc58b293', 1, 'SFTS (중증열성혈소판감소증후군)', '참진드기에 물려 감염되는 바이러스 질환입니다. 산책 후 진드기 확인이 가장 중요한 예방입니다.', '{"animalSigns":["발열, 식욕 저하, 기력 저하","구토·설사","잇몸이 창백하거나 누렇게 보임","증상이 뚜렷하지 않을 수도 있음"],"humanSigns":["진드기 물림 후 보통 1~2주 안에 고열","구토·설사 등 소화기 증상","심한 피로감"],"transmission":["참진드기에 물려 감염","감염된 동물의 혈액·체액에 맨손으로 닿은 사람에게 전파된 사례가 보고됨"],"prevention":["풀숲·산길 산책 뒤 귀 뒤·겨드랑이·발가락 사이 확인","진드기 예방제는 동물병원과 상담해 선택","사람은 긴 옷·기피제 사용, 귀가 후 샤워","아픈 동물을 돌볼 때 장갑 착용"],"humanSeekCare":["진드기에 물린 뒤 2주 안에 고열·소화기 증상이 생기면 의료기관 방문","진료 시 반려동물·야외활동 이력을 알리기"],"animalSeekVet":["야외활동 뒤 발열·기력 저하·식욕 저하가 이어질 때","몸에 붙은 진드기를 발견했을 때(제거는 동물병원에 문의)"],"dont":["진드기를 손으로 눌러 터뜨리기","아픈 동물의 침·혈액을 맨손으로 만지기","증상을 두고 보며 기다리기"]}'::jsonb, '[{"organization":"질병관리청 감염병포털","url":"https://dportal.kdca.go.kr/pot/ii/sttyInftnsds/sttyInftnsds.do","checkedAt":"2026-08-31"},{"organization":"농림축산검역본부","url":"https://www.qia.go.kr","checkedAt":"2026-08-31"}]'::jsonb, '펫안심365 초안 (검수 전)', 'in_review', '초기 작성') on conflict (content_id, version) do nothing;
insert into public.content_versions (id, content_id, version, title, summary, body_json, source_json, author_name, status, change_reason) values ('08952d80-d866-5f7a-8561-b81fc32c93a0', '02ac3db8-4c00-55b4-910f-dd68afe38976', 1, '공수병 (광견병)', '감염된 동물에게 물리거나 긁혀 전파됩니다. 반려견 예방접종과 교상 후 즉시 대응이 핵심입니다.', '{"animalSigns":["평소와 다른 행동(갑작스러운 공격성 또는 이상하게 온순함)","침을 많이 흘리고 삼키기 어려워함","비틀거림·마비"],"humanSigns":["물린 부위의 이상 감각(저림·가려움)","발열·두통","물이나 바람을 무서워하는 증상 등 신경 증상"],"transmission":["감염 동물에게 물리거나 긁힘","감염 동물의 침이 상처·점막에 닿음","국내는 야생동물(너구리 등) 관리가 계속되고 있어 접경 지역에서 주의"],"prevention":["반려견 광견병 예방접종을 정기적으로 실시(법정 예방접종)","야생동물·모르는 동물 만지지 않기","해외에서 동물에게 물리지 않도록 주의"],"humanSeekCare":["동물에게 물리거나 긁혔다면 흐르는 물과 비누로 15분 이상 씻고 바로 의료기관 방문","물었던 동물의 종류·상태·접종 여부를 알리기"],"animalSeekVet":["야생동물과 접촉하거나 물렸을 때","예방접종 시기를 놓쳤을 때"],"dont":["물린 상처를 씻지 않고 두기","야생동물을 손으로 잡거나 먹이 주기","예방접종을 건너뛰기"]}'::jsonb, '[{"organization":"질병관리청 감염병포털","url":"https://dportal.kdca.go.kr/pot/ii/sttyInftnsds/sttyInftnsds.do","checkedAt":"2026-08-31"},{"organization":"농림축산검역본부","url":"https://www.qia.go.kr","checkedAt":"2026-08-31"}]'::jsonb, '펫안심365 초안 (검수 전)', 'in_review', '초기 작성') on conflict (content_id, version) do nothing;
insert into public.content_versions (id, content_id, version, title, summary, body_json, source_json, author_name, status, change_reason) values ('61ad570a-c122-55a9-980d-d511c05663e9', '470b77e0-bf38-561b-844c-42f028ebe5c7', 1, '개 브루셀라증', '개의 생식기 분비물·유산 물질을 통해 사람에게도 전파될 수 있는 세균 감염입니다. 입양·교배 전 검사가 중요합니다.', '{"animalSigns":["유산·사산, 새끼가 약하게 태어남","수컷의 고환 붓기·불임","림프절 붓기","겉으로는 건강해 보일 수 있음"],"humanSigns":["오르내리는 발열","피로·근육통·관절통","두통, 식은땀"],"transmission":["감염견의 유산 물질·태반·생식기 분비물 접촉","감염견의 소변·혈액 접촉","교배를 통한 개 사이 전파"],"prevention":["입양·교배 전 검사 결과 확인","출산·유산 처리 시 장갑 착용, 손 씻기","번식장·동물병원 종사자는 보호장비 사용"],"humanSeekCare":["감염견과 접촉한 뒤 원인 모를 발열·피로가 이어질 때","진료 시 반려견 접촉 이력을 알리기"],"animalSeekVet":["유산·사산이 있었을 때","고환이 붓거나 교배 전 검사가 필요할 때"],"dont":["유산 물질을 맨손으로 치우기","검사 없이 교배하기"]}'::jsonb, '[{"organization":"농림축산검역본부","url":"https://www.qia.go.kr","checkedAt":"2026-08-31"},{"organization":"질병관리청 감염병포털","url":"https://dportal.kdca.go.kr/pot/ii/sttyInftnsds/sttyInftnsds.do","checkedAt":"2026-08-31"}]'::jsonb, '펫안심365 초안 (검수 전)', 'in_review', '초기 작성') on conflict (content_id, version) do nothing;
insert into public.content_versions (id, content_id, version, title, summary, body_json, source_json, author_name, status, change_reason) values ('95670b12-f78f-501a-95e8-8ca4abf7d43a', '4b9dadea-8d55-5935-bcbf-3b44a45a9437', 1, '톡소포자충증', '고양이가 최종숙주인 기생충 감염입니다. 사람은 덜 익힌 고기와 오염된 흙·모래가 주요 경로이며, 화장실 매일 청소로 예방할 수 있습니다.', '{"animalSigns":["대부분 증상이 없음","드물게 발열·식욕 저하·호흡 이상"],"humanSigns":["대부분 증상이 없거나 가벼운 림프절 붓기","임신 중 처음 감염되면 태아에 영향 가능","면역이 약한 사람은 심한 증상 가능"],"transmission":["감염 고양이 대변의 난포낭(배출 후 1~5일이 지나야 감염력이 생김)으로 오염된 흙·모래·채소","덜 익힌 고기 섭취(사람 감염의 주요 경로)","고양이 몸을 만지는 것만으로는 감염되지 않음"],"prevention":["화장실은 매일 치우기(난포낭이 감염력을 갖기 전)","장갑 착용·손 씻기, 임신 중이면 청소를 다른 가족에게 맡기기","고기는 충분히 익히기, 채소는 잘 씻기","고양이에게 날고기 급여 피하기, 실내 생활"],"humanSeekCare":["임신 중 노출이 걱정될 때 산부인과와 상담","면역이 약한 상태에서 발열·림프절 붓기가 있을 때"],"animalSeekVet":["발열·식욕 저하·호흡 이상이 이어질 때","날고기 급여 이력이 있고 컨디션이 나쁠 때"],"dont":["감염이 걱정된다고 고양이를 버리거나 격리하기","날고기 급여","화장실을 며칠씩 방치하기"]}'::jsonb, '[{"organization":"질병관리청 감염병포털","url":"https://dportal.kdca.go.kr/pot/ii/sttyInftnsds/sttyInftnsds.do","checkedAt":"2026-08-31"},{"organization":"농림축산검역본부","url":"https://www.qia.go.kr","checkedAt":"2026-08-31"}]'::jsonb, '펫안심365 초안 (검수 전)', 'in_review', '초기 작성') on conflict (content_id, version) do nothing;
update public.content_cards set current_version_id = '02896c65-1c7c-5214-a35b-0866a9ecef42' where id = '9ad9556a-0b04-51e6-a785-f5d8bc58b293' and current_version_id is null;
update public.content_cards set current_version_id = '08952d80-d866-5f7a-8561-b81fc32c93a0' where id = '02ac3db8-4c00-55b4-910f-dd68afe38976' and current_version_id is null;
update public.content_cards set current_version_id = '61ad570a-c122-55a9-980d-d511c05663e9' where id = '470b77e0-bf38-561b-844c-42f028ebe5c7' and current_version_id is null;
update public.content_cards set current_version_id = '95670b12-f78f-501a-95e8-8ca4abf7d43a' where id = '4b9dadea-8d55-5935-bcbf-3b44a45a9437' and current_version_id is null;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('f17a14c3-3150-5ecc-badc-0be3170824e6', 'animal_protection_call', 'lost_found', '동물보호상담센터', '1577-0954', 'https://www.animal.go.kr', '전국', '운영시간은 전화 연결 시 안내', '유실·유기 동물 발견 신고와 상담.', '2026-08-31', 'https://www.mafra.go.kr', 'active', 10) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('131c931f-8734-554c-9181-85802c9ec31e', 'animal_go_kr_report', 'lost_found', '국가동물보호정보시스템 온라인 신고', null, 'https://www.animal.go.kr', '전국', '24시간(온라인)', '발견 동물 신고, 보호 중인 동물 조회.', '2026-08-31', 'https://www.animal.go.kr', 'active', 20) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('fa631053-3047-550d-b71e-7dc073852563', 'my_pet_lost_registry', 'my_pet_lost', '국가동물보호정보시스템 (동물등록 유실 신고)', null, 'https://www.animal.go.kr', '전국', '24시간(온라인)', '등록동물 유실 신고와 변경 절차. 보호 중인 동물 공고도 함께 확인하세요.', '2026-08-31', 'https://www.animal.go.kr', 'active', 10) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('5de1a2ca-2deb-5ed7-9e8c-f893cacccd1b', 'police_112', 'abuse', '경찰 (112)', '112', null, '전국', '24시간', '진행 중인 학대, 생명이 위험한 상황. 신고자 안전을 먼저 확보하세요.', '2026-08-31', null, 'active', 10) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('46a2fbae-44d5-59b6-8e45-2cd4b6f30c2e', 'local_gov_animal_welfare', 'abuse', '관할 시·군·구청 동물보호 담당부서', null, 'https://www.gov.kr', '관할 지역', '평일 근무시간', '학대 의심 신고·현장 점검. 지자체 대표번호로 연결됩니다. 지역별 번호는 운영자 확인 후 게시됩니다.', null, null, 'pending_verification', 20) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('a7e5ddcf-f39d-54ad-b0d7-26f179c634ba', 'kvma_illegal_practice', 'illegal_practice', '대한수의사회 (불법 동물진료 신고)', null, 'https://www.kvma.or.kr', '전국', null, '무자격 진료·불법 시술 의심. 신고 채널은 운영자 검증 후 게시됩니다.', null, null, 'pending_verification', 10) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('afdd0a35-d32a-52fa-a4a1-dee8426475bc', 'consumer_1372', 'dispute', '1372 소비자상담센터', '1372', 'https://www.ccn.go.kr', '전국', '평일 09:00~18:00', '진료비·서비스 분쟁 상담. 영수증·설명 기록·대화 내역을 보관하세요.', '2026-08-31', null, 'active', 10) on conflict (key) do nothing;
insert into public.official_contacts (id, key, category, organization, phone, url, coverage_area, available_hours, description, verified_at, source_url, status, sort_order) values ('4a8f9fea-4e06-52bf-996e-a90fd6b69188', 'registration_info', 'registration', '국가동물보호정보시스템 (동물등록 안내)', null, 'https://www.animal.go.kr', '전국', '24시간(온라인)', '동물등록 대행기관 찾기와 등록 절차.', '2026-08-31', 'https://www.animal.go.kr', 'active', 10) on conflict (key) do nothing;
insert into public.legal_documents (id, document_type, version, title, effective_at, body, required, status) values ('861491ca-9b91-5b42-924f-04d0502ef2c0', 'terms', '2026-09-24.v1', '서비스 이용약관', '2026-09-24', '※ 본 문서는 운영 초안입니다. 사업자 정보·결제 구조 확정 후 변호사 검토를 거쳐 정식 시행됩니다.

제1조 (목적) 이 약관은 펫안심365(이하 "서비스")의 이용 조건과 절차, 이용자와 운영자의 권리·의무를 정합니다.

제2조 (서비스의 성격) 서비스는 반려동물 돌봄 일정, 기록, 긴급 시 행동 안내, 공식 신고처 연결, 공공데이터 기반 시설 정보를 제공합니다. 서비스는 수의학적 진단·처방·치료 결정을 제공하지 않으며, 보험상품의 가입 권유나 보험금 지급 결정을 하지 않습니다.

제3조 (계정) 이용자는 이메일로 가입하며, 계정 정보를 정확히 유지할 책임이 있습니다. 이용자는 언제든 탈퇴할 수 있고, 탈퇴 시 개인정보 처리방침에 따라 데이터가 삭제됩니다.

제4조 (이용자의 의무) 타인의 개인정보·초상을 무단 게시하지 않으며, 신고 대상자의 실명·주소를 공개하지 않습니다. 서비스의 정보를 상업적으로 무단 복제하지 않습니다.

제5조 (정보의 한계) 시설 운영시간·연락처·동반 조건, 법령·연락처는 바뀔 수 있습니다. 서비스는 출처와 최근 확인일을 표시하며, 이용자는 방문 전 전화로 확인해야 합니다.

제6조 (무료 제공) 긴급 안내·신고 연결·감염병 예방정보는 무료로 제공되며 유료 벽 뒤에 두지 않습니다.

제7조 (약관 변경) 약관을 바꿀 때는 시행일 7일 전(불리한 변경은 30일 전) 공지하며, 동의한 문서 버전은 계정에 기록됩니다.', true, 'published') on conflict (document_type, version) do nothing;
insert into public.legal_documents (id, document_type, version, title, effective_at, body, required, status) values ('9f8438a7-9049-58c4-9ef8-ce718b40b3cb', 'privacy', '2026-09-24.v1', '개인정보 처리방침', '2026-09-24', '※ 본 문서는 운영 초안입니다. 사업자 정보·결제 구조 확정 후 변호사 검토를 거쳐 정식 시행됩니다.

1. 수집 항목: 이메일(필수), 표시 이름(선택), 반려동물 정보(종·이름·생년·체중·질환 등, 이용자 입력), 돌봄 기록·문서(이용자 업로드), 서비스 이용 기록(오류·접속 로그). 주민등록번호와 사람의 진단정보는 수집하지 않습니다.

2. 이용 목적: 계정 관리, 돌봄 일정·기록 제공, 문의 응대, 법령 준수. 건강문서·보험문서·위치·신고정보는 광고 타기팅에 사용하지 않습니다.

3. 보유 기간: 탈퇴 시 지체 없이 삭제합니다. 신고 준비 초안은 저장 시점부터 90일 후 자동 삭제됩니다. 법령이 보존을 요구하는 기록은 해당 기간 보관합니다.

4. 제3자 제공·처리위탁: 인증·데이터베이스·파일 저장은 Supabase에 위탁됩니다. 지도·주소 검색 사용 시 Kakao에 검색어가 전송됩니다. 그 외 제3자 제공은 이용자 동의 없이 하지 않습니다.

5. 이용자 권리: 열람·정정·삭제·처리정지·데이터 내려받기를 요청할 수 있으며, 계정 화면의 탈퇴 기능으로 직접 삭제할 수 있습니다.

6. 안전조치: 행 수준 보안(RLS)으로 본인 데이터만 접근 가능, 문서는 비공개 저장소와 짧은 만료 서명 URL로만 접근, 관리자 접근은 감사로그에 기록됩니다.

7. 개인정보 보호책임자: (사업자 확정 후 기재)', true, 'published') on conflict (document_type, version) do nothing;
insert into public.legal_documents (id, document_type, version, title, effective_at, body, required, status) values ('62dcf65a-50a6-51b3-9be9-02e3a8b11a00', 'location', '2026-09-24.v1', '위치정보 안내', '2026-09-24', '※ 본 문서는 운영 초안입니다. 사업자 정보·결제 구조 확정 후 변호사 검토를 거쳐 정식 시행됩니다.

1. 위치 권한은 이용자가 "내 주변 찾기" 버튼을 눌렀을 때만 브라우저를 통해 요청합니다. 앱은 백그라운드에서 위치를 수집하지 않습니다.

2. 정밀 좌표는 이용자 계정에 저장하지 않으며, 검색 결과를 계산하는 동안만 브라우저 안에서 사용됩니다. 정밀 위치 저장 기능은 기본적으로 꺼져 있고, 별도 동의와 운영자 승인 없이는 켜지지 않습니다.

3. 위치 권한을 거부해도 주소·지하철역·행정동 입력으로 같은 기능을 쓸 수 있습니다.

4. 신고 준비 도구는 행정동 수준의 대략적 위치 문구만 저장하며, 이용자가 원할 때만 저장됩니다.', true, 'published') on conflict (document_type, version) do nothing;
insert into public.legal_documents (id, document_type, version, title, effective_at, body, required, status) values ('8ab928ed-b56c-5f1c-90e0-7936ab1ad36a', 'copyright', '2026-09-24.v1', '저작권·이용자 게시물 정책', '2026-09-24', '※ 본 문서는 운영 초안입니다. 사업자 정보·결제 구조 확정 후 변호사 검토를 거쳐 정식 시행됩니다.

1. 서비스는 공공데이터(공공데이터포털·국가동물보호정보시스템·한국관광공사 등), 이용자가 직접 제공한 자료, 적법한 라이선스의 자료만 사용합니다. 검색 포털의 리뷰·사진·장소정보를 복제하지 않습니다.

2. 공공데이터·관광 사진은 레코드별로 출처와 라이선스를 기록하고 화면에 표시합니다.

3. 이용자가 올리는 사진·문서는 본인이 권리를 보유하거나 사용 허락을 받은 것이어야 하며, 타인의 초상·개인정보가 드러나지 않아야 합니다.

4. 권리 침해 신고: 침해 자료의 위치, 권리 증빙, 연락처를 운영자에게 보내면 확인 후 지체 없이 조치합니다.

5. 서비스의 건강·감염병 콘텐츠는 출처를 밝히면 비상업적 공유가 가능하나, 검수일이 지난 내용은 공유하지 마세요.', true, 'published') on conflict (document_type, version) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('38e9dda8-14ba-5e43-bf92-885b36950917', 'animal_hospital', '예시 동물병원 A', '서울특별시 중구 예시로 1 (예시 데이터)', 37.5672, 126.9794, 'wgs84', '02-000-0001', 'open', 'demo_fixture', 'demo-h1', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('38e9dda8-14ba-5e43-bf92-885b36950917', '{"note":"운영시간 미확인"}'::jsonb, '{}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('7d8fed1e-a99a-5d2f-ab13-dec88309aaa5', 'animal_hospital', '예시 동물병원 B', '서울특별시 중구 예시로 22 (예시 데이터)', 37.5641, 126.9752, 'wgs84', '02-000-0002', 'open', 'demo_fixture', 'demo-h2', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('7d8fed1e-a99a-5d2f-ab13-dec88309aaa5', '{"weekday":"09:00-19:00"}'::jsonb, '{}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('e91e96d9-18ec-5dd2-a5ad-cb8d16b09261', 'animal_hospital', '예시 동물병원 C (폐업 이력)', '서울특별시 종로구 예시길 3 (예시 데이터)', 37.5701, 126.982, 'wgs84', null, 'closed', 'demo_fixture', 'demo-h3', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('e91e96d9-18ec-5dd2-a5ad-cb8d16b09261', '{}'::jsonb, '{}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('307320fd-c669-529d-b7a8-8a6b2d532d27', 'animal_pharmacy', '예시 동물약국', '서울특별시 중구 예시로 5 (예시 데이터)', 37.5655, 126.981, 'wgs84', '02-000-0003', 'open', 'demo_fixture', 'demo-p1', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('307320fd-c669-529d-b7a8-8a6b2d532d27', '{}'::jsonb, '{}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('21f04ed7-9337-50c0-8458-13fb6a296f50', 'shelter', '예시 동물보호센터', '서울특별시 종로구 예시길 10 (예시 데이터)', 37.573, 126.976, 'wgs84', '02-000-0004', 'open', 'demo_fixture', 'demo-s1', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('21f04ed7-9337-50c0-8458-13fb6a296f50', '{"weekday":"10:00-17:00"}'::jsonb, '{}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('d6fdbca5-9e53-589d-8dff-0065e2ad4727', 'pet_cafe', '예시 반려동물 동반 카페', '서울특별시 중구 예시로 30 (예시 데이터)', 37.562, 126.984, 'wgs84', '02-000-0005', 'open', 'demo_fixture', 'demo-c1', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('d6fdbca5-9e53-589d-8dff-0065e2ad4727', '{"daily":"11:00-21:00"}'::jsonb, '{"indoor":true,"outdoor":false,"size_limit":"미확인","carrier":null,"leash":true,"vaccination_proof":null,"extra_fee":"미확인","last_confirmed_at":null}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
insert into public.facilities (id, facility_type, name, address, lat, lng, coord_source, phone, business_status, source_system, source_id, source_updated_at, license, is_example, last_synced_at) values ('5108d495-a8aa-5bfe-a861-ff2b8ae4559f', 'park', '예시 공원 반려견 놀이터', '서울특별시 중구 예시로 50 (예시 데이터)', 37.56, 126.97, 'wgs84', null, 'open', 'demo_fixture', 'demo-k1', '2026-09-24T00:00:00.000Z', '예시 데이터 (실제 업체 아님)', true, '2026-09-24T00:00:00.000Z') on conflict (source_system, source_id) do nothing;
insert into public.facility_details (facility_id, hours_json, pet_access_json, emergency_status, specialty_status, hours_status) values ('5108d495-a8aa-5bfe-a861-ff2b8ae4559f', '{"daily":"06:00-22:00"}'::jsonb, '{"indoor":false,"outdoor":true,"size_limit":"미확인","leash":true,"vaccination_proof":"미확인","extra_fee":"무료(미확인)","last_confirmed_at":null}'::jsonb, 'unverified', 'unverified', 'unverified') on conflict (facility_id) do nothing;
commit;
