"""「밧모섬의 증인」 Flow·Veo 촬영 대본 — 장면(가사 단락)별 화면 설명.

SCENES[편][장면 번호] = [(영어 설명, 한글 요약), …]
한 장면 안의 컷들이 이 목록을 차례로 돌려 쓰고, 컷마다 카메라 움직임을 바꾼다 (musical.flow_prompts).
"""
from __future__ import annotations

J = ("the aged apostle John (about 90 years old, long white beard and white hair, coarse brown hooded wool robe, "
     "rope belt, wooden staff)")
GOD = ("a vast column of warm golden light with soft rainbow-tinted rays pouring down from parted clouds "
       "(the Voice of God, never shown as a person)")

STYLE = ("Epic biblical feature film, photorealistic, anamorphic widescreen, volumetric god rays through atmospheric haze, "
         "floating dust particles in the light, rich golden and deep blue color grade, shallow depth of field. "
         "People are seen from behind, in silhouette or at a distance, never in facial close-up. "
         "Jesus is never depicted. No text, no subtitles, no logos, no watermark.")

CHAR = {"요한": f"Recurring character: {J}."}

SCENES: dict[str, dict[int, list[tuple[str, str]]]] = {
    "2-1": {
        0: [(f"{J} stands on a rocky cliff of Patmos at dusk, seen from behind, gazing at a vision of a vast modern city skyline forming in the clouds over the Aegean sea", "밧모섬 절벽의 요한, 구름 속에 떠오르는 현대 도시 환상"),
            (f"{J} walks slowly along the cliff edge leaning on his staff, wind moving his robe, the city vision glowing in the sky", "지팡이를 짚고 절벽을 걷는 요한"),
            (f"detail of {J}'s weathered hands gripping the wooden staff, then tilt up to his silhouette against the glowing sky", "지팡이 쥔 손 → 하늘 앞 실루엣"),
            (f"{J} kneels on the rock and raises both arms toward the city vision, seen from a distance", "무릎 꿇고 두 팔을 드는 요한")],
        1: [(f"{GOD} descending through storm clouds over a modern city at night, five roads diverging below and glowing one by one", "폭풍 구름을 뚫고 내려오는 빛기둥, 다섯 갈래 길"),
            (f"{J}, small in the frame, bows low on the cliff as the column of golden light stands before him", "빛기둥 앞에 엎드린 요한")],
        2: [("a church surrounded by high stone walls with locked iron gates, the people inside turning their backs to a bustling city outside, overcast light", "높은 담 안에 갇힌 교회, 세상에 등 돌린 사람들"),
            ("worshippers inside a walled courtyard singing with eyes closed while beyond the wall the city streets are grey and crowded", "담 안에서 노래하는 사람들, 담 너머 회색 도시")],
        3: [("a single oil lamp hidden under a large woven basket on a wooden table in a dark room, a dark city waiting outside the window; a golden ray reaches in and lifts the basket", "바구니 아래 숨긴 등불을 빛이 들추어 냄"),
            (f"{GOD} falling onto a city street at night, people stopping and looking up", "밤거리에 쏟아지는 빛, 올려다보는 사람들")],
        4: [("a church interior turned into a flashy concert hall with neon lights and giant LED screens, crowd seen from behind, a plain wooden cross dim in a corner", "네온과 대형 화면의 콘서트장이 된 교회, 구석의 십자가"),
            ("the camera moves through the dancing crowd toward a forgotten wooden cross standing in shadow", "군중 사이로 잊힌 나무 십자가"),
            ("confetti falling through colored stage lights while the wooden cross stays in darkness", "색 조명 속 꽃가루, 어둠 속 십자가")],
        5: [(f"{GOD} breaking through the ceiling of the neon concert hall, the screens flickering off one by one", "천장을 뚫고 들어온 빛, 화면이 하나씩 꺼짐"),
            ("the plain wooden cross now alone in a beam of warm light in the emptied hall", "텅 빈 홀, 빛 속에 홀로 선 십자가")],
        6: [("a split world: a bright Sunday church service on one side and a grey Monday office with tired workers on the other, divided by a thin wall of light", "주일 예배와 월요일 사무실을 가르는 빛의 벽"),
            ("office workers in suits walk out of a church into grey rain under umbrellas, their Bibles closed", "우산 쓰고 교회를 나서는 직장인들"),
            ("hands slide a Bible into a desk drawer and close it, then turn toward the cold glow of a computer screen", "성경을 서랍에 넣고 모니터로 돌아서는 손")],
        7: [(f"aerial view at sunrise, {GOD} spreading over office towers, family homes and a parliament building", "사무실·가정·국회 위로 퍼지는 빛"),
            ("golden light entering an office window and moving across rows of empty desks", "사무실 책상 위로 번지는 빛")],
        8: [("a businessman in a suit stands half in church candlelight and half in a dark alley counting money, his shadow split in two, seen from a distance", "반은 촛불, 반은 어두운 골목에 선 사업가 — 두 얼굴"),
            ("two shadows of the same man walk in opposite directions on a wet street at night", "젖은 밤거리, 반대로 걸어가는 두 그림자"),
            ("a man in a suit removes a church name badge and puts it in his pocket before entering a smoky backroom, seen from behind", "교회 이름표를 떼고 뒷방으로 들어가는 남자")],
        9: [("a stormy sky over a modern city with lightning and a column of fiery golden light", "번개와 불기둥이 선 도시 하늘"),
            ("one hand drops coins into an offering box while another hand takes money from a poor worker, dramatic chiaroscuro, hands only", "헌금하는 손과 빼앗는 손"),
            ("the businessman falls to his knees on the wet street as the light hits him, seen from behind", "빛을 맞고 무릎 꿇는 사업가"),
            ("rain falling in slow motion through beams of light over the city", "빛줄기 사이로 느리게 떨어지는 비")],
        10: [("people walk out of a church into city streets carrying lanterns and bread as sunrise breaks over skyscrapers", "등불과 빵을 들고 도시로 나가는 사람들"),
             ("volunteers handing bread and warm drinks to homeless people under a bridge at dawn, seen from a distance", "새벽 다리 밑에서 빵을 나누는 사람들"),
             ("office workers pausing to pray quietly at their desks in soft morning light, seen from behind", "아침 책상에서 조용히 기도하는 직장인들")],
        11: [("aerial view of a city at dawn as many small warm lights switch on and spread through its streets like a living network", "도시 곳곳에 켜지는 작은 불빛들"),
             (f"{GOD} resting gently over the city as the warm lights multiply", "도시 위에 머무는 빛")],
        12: [(f"{J} on the cliff raising his wooden staff toward the sunrise, seen from behind", "해돋이를 향해 지팡이를 드는 요한"),
             (f"{J} bowing his head in thanks, sunrise rim light on his white hair, profile silhouette", "감사로 고개 숙인 요한의 옆모습")],
        13: [("a great crowd fills the city streets with hands raised as golden light rays burst over the skyline", "손 들고 거리를 가득 채운 군중"),
             ("radiant rainbow light rays pour from heaven over a modern city and a crowd of worshippers", "도시와 군중 위로 쏟아지는 무지개빛"),
             ("the camera cranes up from the crowd to reveal the whole city glowing at sunrise", "군중에서 도시 전체로 솟아오르는 화면")],
    },
    "2-2": {
        0: [(f"{J} stands on a rocky cliff of Patmos above the Aegean sea at dawn, seen from behind and far away, golden rays through clouds", "새벽 밧모섬 절벽의 요한"),
            (f"{J} unrolls a scroll on a flat rock by the sea, wind lifting its edges", "바닷가 바위에서 두루마리를 펴는 요한"),
            (f"{J} lifts his eyes to the sky as the clouds slowly part", "갈라지는 구름을 올려다보는 요한")],
        1: [(f"{GOD} entering a dark vaulted stone room in ancient Smyrna where early Christians kneel by oil lamps", "서머나의 어두운 돌방, 기도하는 성도들 위로 내리는 빛"),
            ("seven golden lampstands glowing in the haze as warm light descends", "빛 속에 타오르는 일곱 금 촛대"),
            ("poor early Christians in patched clothes share a small loaf of bread by lamplight, hands only", "등불 아래 빵을 나누는 가난한 손들")],
        2: [("early Christians in a dim Roman prison with stone arches and iron bars pray with raised hands, light through a small high window, chains on the floor", "로마 감옥에서 손 들고 기도하는 성도들"),
            ("Roman soldiers seen from behind lead a calm believer through a torch-lit stone corridor", "횃불 복도로 끌려가는 담담한 성도"),
            ("a believer walks alone toward the bright light at the end of an arena tunnel, seen from behind", "경기장 통로 끝 빛을 향해 걷는 성도")],
        3: [("a huge ancient wooden door slowly opens in a stone hall, brilliant white light pouring through the doorway onto small humble people kneeling before it", "거대한 문이 열리며 쏟아지는 빛"),
            ("detail of an ancient golden key turning in an iron lock inside a beam of light", "빛 속에서 돌아가는 황금 열쇠"),
            (f"{GOD} beyond the open door, dust swirling in the light", "열린 문 너머의 빛")],
        4: [("humble early Christians walk together through a great open stone gate toward a sunrise over green hills, long shadows, golden light", "열린 성문을 지나 해돋이로 걷는 성도들"),
            ("a small child and an old woman walk hand in hand through the open gate, seen from behind", "손잡고 성문을 지나는 아이와 할머니"),
            ("a line of people climbing a hill path at dawn, each carrying a small oil lamp", "작은 등불을 들고 언덕을 오르는 행렬")],
        5: [(f"{J} stands on a rock with one arm raised before a crowd of early Christians under a red and gold sunset, seen from behind the crowd", "노을 아래 성도들 앞에서 팔을 든 요한"),
            (f"{J} lifts his staff high as the crowd raises their hands, wide shot", "지팡이를 높이 드는 요한과 환호하는 무리")],
        6: [(f"{J} kneels alone on dark rocks by the sea at night under moonlight, seen from far away, blue tones", "달빛 아래 홀로 무릎 꿇은 요한"),
            (f"waves crash against black rocks, {J} a small bowed silhouette", "파도 치는 바위 위 작은 실루엣")],
        7: [("a large modern church auditorium at night in dim blue light, scattered office workers in suits kneeling between rows of empty chairs, city lights through tall windows", "밤의 텅 빈 대예배실, 무릎 꿇은 직장인들"),
            ("a modern office floor at night, workers standing silent at their desks in cold light, one man holding a small wooden cross, seen from a distance", "밤 사무실, 작은 나무 십자가를 쥔 직장인"),
            ("a woman in office clothes prays alone on a subway platform as trains rush past, seen from behind", "지하철 승강장에서 홀로 기도하는 여성"),
            ("an empty church parking lot in the rain at night, a single car headlight on", "비 내리는 빈 교회 주차장"),
            ("a small cross necklace resting in an open palm beside a dark phone screen, detail", "손바닥 위 작은 십자가 목걸이")],
        8: [("warm golden light rays pour through tall windows of a modern church onto kneeling people who slowly lift their heads", "창으로 쏟아지는 빛, 고개를 드는 사람들"),
            (f"{GOD} flooding a modern office at night, loose papers drifting in the light", "밤 사무실을 가득 채우는 빛"),
            ("open hands lifted into a beam of light, dust sparkling around them, hands only", "빛 속으로 펼쳐 든 손들")],
        9: [(f"{J} with arms wide open on a cliff at sunrise over the Aegean sea, seen from behind, glorious light rays", "해돋이 절벽에서 두 팔 벌린 요한"),
            (f"{J} walks toward the sunrise along the cliff path, robe glowing at the edges", "해를 향해 걸어가는 요한")],
        10: [("a great multitude of ancient and modern people stand together with hands raised in a vast sunlit valley before a glowing golden gate in the sky", "하늘 황금문 앞, 고대와 현대 성도의 연합"),
             ("a huge crowd worships on a hillside with hands raised as radiant rainbow light rays burst from the heavens", "언덕 위 군중에게 쏟아지는 무지개빛"),
             ("robed early Christians and modern office workers walk side by side toward the light, seen from behind", "나란히 빛으로 걷는 초대교회 성도와 직장인"),
             ("the camera cranes high over the multitude as the golden gate glows brighter", "군중 위로 높이 솟는 화면")],
    },
    "2-3": {
        0: [(f"{J} kneels on dark rocks by a stormy sea with lightning, seen from far away", "번개 치는 바다, 바위에 무릎 꿇은 요한"),
            (f"{J} rises against the wind, robe whipping, staff planted in the rock", "바람을 맞서 일어서는 요한"),
            ("lightning illuminates five distant ancient cities along a dark coastline", "번개에 드러나는 다섯 고대 도시")],
        1: [("the ruins of the ancient library of Celsus in Ephesus at dusk, a golden lampstand whose flame is fading", "에베소 셀수스 도서관 폐허, 꺼져 가는 촛대"),
            (f"{GOD} over the Ephesus ruins as the weak flame flickers", "에베소 폐허 위의 빛, 흔들리는 불꽃")],
        2: [("people kneel in repentance in a large empty modern church hall full of banners and stage equipment, one warm light from above", "배너와 무대장비 가득한 홀, 회개하는 사람들"),
            ("hands relight a small oil lamp from another flame, detail", "다른 불꽃으로 작은 등불을 다시 켜는 손"),
            ("people slowly rise to their feet holding glowing lamps", "등불을 들고 천천히 일어서는 사람들")],
        3: [("the ancient acropolis of Pergamum on a hill with a pagan altar under a stormy red sky, a sword-shaped beam of light in the clouds", "버가모 신전과 칼 모양의 빛"),
            ("the sword of light cuts through the red storm clouds above the altar", "붉은 구름을 가르는 빛의 칼")],
        4: [("people smash golden idols of money and power in a dark hall, sparks flying, dramatic light, seen from behind", "돈과 권력의 황금 우상을 부수는 사람들"),
            ("gold coins scatter across a stone floor in slow motion", "돌바닥에 흩어지는 금화"),
            ("a large golden statue topples and shatters in a beam of light", "빛 속에 넘어져 깨지는 황금상")],
        5: [("the ancient marketplace of Thyatira with hanging purple cloth at dusk, long shadows, a burning light in the clouds", "두아디라 시장, 자주색 천, 불타는 구름"),
            ("purple cloth billows in the wind as the fiery light approaches", "다가오는 불빛에 흩날리는 자주 천")],
        6: [("people throw treasures into a fire at night as a bright morning star rises in the dawn sky", "보물을 불에 던지는 사람들, 떠오르는 새벽별"),
            ("a brilliant morning star rises over the hills, its light falling on the kneeling crowd", "언덕 위 새벽별, 무릎 꿇은 무리")],
        7: [("the ancient city of Sardis on a cliff at night, grand buildings with no lights, lifeless, cold moonlight", "불 꺼진 사데 도시, 차가운 달빛"),
            ("an empty grand hall covered in dust and cobwebs, a single thin beam of light", "먼지와 거미줄의 빈 대전, 한 줄기 빛")],
        8: [("a crowd rises from sleep in a dark church as dawn light enters, people putting on white robes", "새벽빛에 깨어나 흰옷을 입는 사람들"),
            ("white robes glowing as people step out into the morning light, seen from behind", "흰옷 입고 아침 빛으로 나가는 무리")],
        9: [("a rich ancient city of Laodicea with a Roman aqueduct and villas under a hazy sky", "수도교와 별장이 늘어선 라오디게아"),
            ("a large closed wooden door with warm light glowing around its edges, dust trembling on it as if someone knocks from outside", "문틈으로 새는 빛, 두드리는 듯 떨리는 문"),
            ("lukewarm water trickling from a broken Roman aqueduct into a stagnant pool", "수도교에서 흘러내리는 미지근한 물")],
        10: [("a wealthy church hall with golden decorations where people weep and open a large wooden door toward warm light", "금장식 교회, 울며 문을 여는 사람들"),
             ("warm light floods through the opened door over the gold decorations, people stepping into it", "열린 문으로 쏟아지는 빛 속으로 들어가는 사람들")],
        11: [(f"{J} stands on a high rock shouting with arms raised in a storm, seen from behind", "폭풍 속 높은 바위에서 외치는 요한")],
        12: [("five groups of people from five ancient cities walk together toward a rising sun", "해를 향해 함께 걷는 다섯 교회"),
             ("five small flames join into one great flame in the dawn light", "다섯 불꽃이 하나로 합쳐짐")],
        13: [("a modern congregation rises to their feet with hands raised in a large church as golden light rays pour down", "손 들고 일어서는 현대 교회"),
             ("office workers and families stand together in the aisle, light pouring over them, seen from behind", "통로에 함께 선 직장인과 가족들")],
        14: [("a vast crowd on a hillside with hands raised as radiant rainbow light rays burst from heaven", "언덕 위 군중에게 쏟아지는 무지개빛"),
             ("seven golden lampstands glow in the sky above a worshipping multitude", "군중 위 하늘에 빛나는 일곱 금 촛대")],
    },
}
